name: build and deploy # workflow 名称
on:
  push: # push 事件触发
    branches: [master] # 只在 master 分支有新的 push 情况下触发

env:
  TARGET_DIR: /www/wwwroot/ # 打包好的项目目录上传位置
  PROJECT_DIR: template-be.araden.top # 打包好的项目目录要改成的名字
  NODE_VERSION: 18
  PNPM_VERSION: 8
  REMOTE_USER: root

jobs:
  build-and-deploy: # job 名称
    runs-on: ubuntu-latest # 执行 workflow 所需的操作系统环境
    steps:
      - name: checkout
        uses: actions/checkout@v3 # 使用切换分支的 action 操作

      - name: pnpm setup
        uses: pnpm/action-setup@v2 # 初始化 pnpm
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      # IF USE DATABASE
      # - name: build
      #   run: pnpm install && pnpm db:generate && pnpm build
      - name: build
        run: pnpm install && pnpm build

      # IF USE DATABASE
      # - name: deploy prepare # Github Action 虚拟机上的操作
      #   run: |
      #     mv dist ${{ env.PROJECT_DIR }}
      #     cp -r prisma/ package.json ${{ env.PROJECT_DIR }}/
      #     cd ${{ env.PROJECT_DIR }}
      #     echo ${{ secrets.DATABASE_ENV }} > .env
      - name: deploy prepare # Github Action 虚拟机上的操作
        run: |
          mv dist ${{ env.PROJECT_DIR }}
          cp -r package.json ${{ env.PROJECT_DIR }}/

      - name: deploy
        uses: easingthemes/ssh-deploy@main # 使用 ssh 上传文件的 action 操作
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }} # ssh 密钥对中的私钥
          REMOTE_HOST: ${{ secrets.REMOTE_HOST  }} # 服务器主机 ip
          REMOTE_USER: ${{ env.REMOTE_USER }} # 服务器用户名
          SOURCE: '${{ env.PROJECT_DIR }}' # 要进行上传的文件目录
          TARGET: ${{ env.TARGET_DIR }} # 要进行部署的生产环境目录
          ARGS: '-rltgoDzvO'
          SCRIPT_AFTER: | # 上传后的操作：安装依赖，迁移数据库
            cd ${{ env.TARGET_DIR }}${{ env.PROJECT_DIR }}
            npm i
            pnpm dlx prisma migrate dev --name migration
            pm2 reload all
